name: Koorioni
main: jp._RS_.Koorioni.Main
version: 0.1.0
commands:
  k:
    description: Commands for Koorioni
    usage: /<command> [args]...
  s:
    description: toggle autosneak
    usage: /<command>
